import assert from 'node:assert/strict'
import { mkdir } from 'node:fs/promises'
import { resolve } from 'node:path'
import { chromium } from '@playwright/test'

const base = process.env.AUTODECISION_UI_URL || 'http://127.0.0.1:5173'
const output = resolve('../../.codex-work/ui-verification')
await mkdir(output, { recursive: true })
const browser = await chromium.launch({ headless: true, ...(process.platform === 'win32' ? { channel: 'msedge' } : {}) })
const errors = []
const timings = []
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
  page.on('pageerror', error => errors.push(error.message))
  await page.goto(`${base}/?demo=1`)
  await page.locator('.graph-node').first().waitFor()
  assert.equal(await page.locator('.graph-node').count(), 20)
  assert.ok(await page.locator('.fusion-edge').count() >= 4)
  await page.getByRole('button', { name: '适应全部节点', exact: true }).click()
  const picked = page.locator('.graph-node').nth(2)
  const pickedId = (await picked.getAttribute('title')).split(' · ')[0]
  await picked.click()
  assert.equal(await page.locator('.inspector-identity').innerText(), pickedId)
  await page.getByRole('combobox', { name: '筛选搜索动作', exact: true }).selectOption('fusion')
  assert.ok(await page.locator('.graph-node.action-fusion').count() > 0)
  assert.equal(await page.locator('.graph-node:not(.action-fusion)').count(), 0)
  await page.getByRole('combobox', { name: '筛选搜索动作', exact: true }).selectOption('all')
  await page.getByRole('combobox', { name: '筛选节点状态', exact: true }).selectOption('bug')
  assert.ok(await page.locator('.graph-node.state-bug').count() > 0)
  assert.equal(await page.locator('.graph-node:not(.state-bug)').count(), 0)
  await page.getByRole('combobox', { name: '筛选节点状态', exact: true }).selectOption('all')
  const zoomBefore = await page.locator('.graph-zoom').innerText()
  await page.getByRole('button', { name: '放大搜索图', exact: true }).click()
  assert.notEqual(await page.locator('.graph-zoom').innerText(), zoomBefore)
  await page.getByRole('button', { name: '缩小搜索图', exact: true }).click()
  assert.equal(await page.locator('.graph-zoom').innerText(), zoomBefore)
  await page.getByRole('button', { name: '定位最佳方案', exact: true }).click()
  await page.getByRole('button', { name: '代码', exact: true }).click()
  await page.locator('.inspector-code').waitFor()
  await page.getByRole('button', { name: '概览', exact: true }).click()
  await page.screenshot({ path: resolve(output, 'desktop.png'), fullPage: true })
  const viewport = page.getByRole('group', { name: '蒙特卡洛搜索图工作区' })
  const camera = page.locator('.graph-canvas > g')
  const before = await camera.getAttribute('transform')
  const bounds = await viewport.boundingBox()
  await page.mouse.move(bounds.x + 30, bounds.y + 35)
  await page.mouse.down(); await page.mouse.move(bounds.x + 125, bounds.y + 70, { steps: 3 }); await page.mouse.up()
  assert.notEqual(await camera.getAttribute('transform'), before)
  await page.getByRole('button', { name: '任务重放', exact: true }).click()
  await page.getByRole('region', { name: '任务重放控制' }).waitFor()
  const track = page.getByRole('slider', { name: '重放进度' })
  const max = Number(await track.getAttribute('max'))
  assert.ok(max > 20000)
  const seek = async value => track.evaluate((element, next) => { element.value = String(next); element.dispatchEvent(new Event('input', { bubbles: true })) }, value)
  await seek(max)
  await page.getByRole('tab', { name: '自动机器学习', exact: true }).click()
  assert.equal(await page.locator('.graph-node').count(), 20)
  await seek(0)
  assert.equal(await page.locator('.graph-node').count(), 0)
  await page.getByRole('button', { name: '下一事件', exact: true }).click()
  await page.getByRole('button', { name: '上一事件', exact: true }).click()
  await page.getByRole('button', { name: '播放重放', exact: true }).click()
  await page.waitForTimeout(150)
  await page.getByRole('button', { name: '暂停重放', exact: true }).click()
  const paused = await track.inputValue()
  await page.waitForTimeout(100)
  assert.equal(await track.inputValue(), paused)
  for (let i = 0; i < 8; i++) {
    const start = performance.now(); await seek(max * (0.4 + i * .05)); timings.push(performance.now() - start)
  }
  const followNode = page.getByRole('checkbox', { name: '跟随新节点', exact: true })
  await followNode.check()
  await page.getByRole('combobox', { name: '筛选搜索动作', exact: true }).selectOption('fusion')
  assert.equal(await followNode.isChecked(), false)
  await seek(max * .9)
  assert.equal(await page.getByRole('combobox', { name: '筛选搜索动作', exact: true }).inputValue(), 'fusion')
  await followNode.check()
  await page.getByRole('textbox', { name: '搜索节点', exact: true }).fill('candidate-19')
  assert.equal(await followNode.isChecked(), false)
  await seek(max)
  assert.equal(await page.getByRole('textbox', { name: '搜索节点', exact: true }).inputValue(), 'candidate-19')
  await followNode.check()
  await page.screenshot({ path: resolve(output, 'replay-desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.waitForTimeout(200)
  await page.screenshot({ path: resolve(output, 'replay-mobile.png'), fullPage: true })
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true)
  await page.getByRole('button', { name: '退出重放', exact: true }).click()
  await page.getByRole('button', { name: '任务列表', exact: true }).click()
  assert.ok(await page.locator('.app-sidebar.opened').isVisible())
  await page.keyboard.press('Escape')
  assert.equal(await page.locator('.app-sidebar.opened').count(), 0)
  await page.screenshot({ path: resolve(output, 'mobile.png'), fullPage: true })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('tab', { name: '任务定义', exact: true }).click()
  await page.locator('.artifact-prose').waitFor()
  assert.ok((await page.locator('.artifact-prose').textContent()).includes('Evaluation'))
  await page.getByRole('button', { name: '查看源文件', exact: true }).click()
  assert.ok((await page.locator('.artifact-preview > pre').textContent()).includes('#'))
  await page.getByRole('button', { name: '文档预览', exact: true }).click()
  await page.screenshot({ path: resolve(output, 'task-definition.png'), fullPage: true })
  await page.getByRole('tab', { name: '报告生成', exact: true }).click()
  await page.locator('.markdown-body').waitFor()
  await page.getByRole('button', { name: '下载报告', exact: true }).waitFor()
  await page.screenshot({ path: resolve(output, 'report.png'), fullPage: true })
  await page.locator('.workspace-topbar').getByRole('button', { name: '全局设置', exact: true }).click()
  const settings = page.getByRole('dialog', { name: '全局设置', exact: true })
  await settings.waitFor()
  await page.waitForTimeout(200)
  await page.screenshot({ path: resolve(output, 'settings-desktop.png') })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.waitForTimeout(200)
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true)
  assert.equal(await settings.evaluate(element => element.scrollWidth <= element.clientWidth), true)
  await page.screenshot({ path: resolve(output, 'settings-mobile.png') })
  await page.keyboard.press('Escape')
  await settings.waitFor({ state: 'hidden' })

  const fixture = await page.evaluate(async () => {
    const data = await import('/src/utils/demoRecording.ts')
    return { task: data.demoTask, snapshot: data.demoSnapshot, recording: data.demoRecording }
  })
  const deletionPage = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
  deletionPage.on('pageerror', error => errors.push(error.message))
  let fixtureTasks = ['Replay fixture A', 'Replay fixture B'].map((name, i) => ({
    ...fixture.task, id: `fixture-${i}`, task_name: name, created_at: i + 1,
    config: { ...fixture.task.config, task_name: name },
  }))
  // Intercept every API request so this destructive UI regression cannot touch real tasks.
  await deletionPage.route('**/api/**', async route => {
    const request = route.request()
    const path = new URL(request.url()).pathname
    const taskId = path.split('/')[3]
    const task = fixtureTasks.find(item => item.id === taskId)
    let data = {}
    if (request.method() === 'DELETE') {
      fixtureTasks = fixtureTasks.filter(item => item.id !== taskId)
      data = { status: 'deleted', deleted_files: [] }
    } else if (path === '/api/tasks') data = fixtureTasks
    else if (path.endsWith('/snapshot')) data = { ...fixture.snapshot, task }
    else if (path.endsWith('/replay')) data = { ...fixture.recording, task_id: taskId, task_name: task.task_name }
    await route.fulfill({ json: data })
  })
  await deletionPage.goto(base)
  await deletionPage.getByRole('button', { name: 'Replay fixture A 已完成', exact: true }).click()
  await deletionPage.getByRole('button', { name: '任务重放', exact: true }).click()
  const replayControls = deletionPage.getByRole('region', { name: '任务重放控制' })
  await replayControls.waitFor()
  await deletionPage.getByRole('button', { name: '删除当前任务', exact: true }).click()
  await deletionPage.getByRole('button', { name: '确认删除', exact: true }).click()
  await replayControls.waitFor({ state: 'hidden' })
  await deletionPage.getByRole('heading', { name: 'Replay fixture B', exact: true }).waitFor()
  assert.equal(fixtureTasks.length, 1)
  await deletionPage.close()
  assert.deepEqual(errors, [])
  console.log(JSON.stringify({ passed: true, desktop: '1440x1000', mobile: '390x844', graphNodes: 20, seekRoundtripMs: timings.map(Math.round), browserErrors: errors, screenshots: output }, null, 2))
} finally { await browser.close() }
